// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwKvSIgLGUAn7mfuj95gqcFD71Q-_JGk',
    appId: '1:958405241222:web:1fb5fe4886a64c2289e407',
    messagingSenderId: '958405241222',
    projectId: 'tokosaya-ef173',
    authDomain: 'tokosaya-ef173.firebaseapp.com',
    storageBucket: 'tokosaya-ef173.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwHBAqg1KsPfmkdwO0aqP8pm6EKbZyeqA',
    appId: '1:958405241222:android:9737fc69187cd7f089e407',
    messagingSenderId: '958405241222',
    projectId: 'tokosaya-ef173',
    storageBucket: 'tokosaya-ef173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuAOY6g1drSjPzJXZqbaB9g2ixCf2BcRg',
    appId: '1:958405241222:ios:d930ad66a6d7e99489e407',
    messagingSenderId: '958405241222',
    projectId: 'tokosaya-ef173',
    storageBucket: 'tokosaya-ef173.appspot.com',
    iosClientId: '958405241222-0976ati127989cdt1ouiga2vnrbsvbs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAkhirToko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuAOY6g1drSjPzJXZqbaB9g2ixCf2BcRg',
    appId: '1:958405241222:ios:d930ad66a6d7e99489e407',
    messagingSenderId: '958405241222',
    projectId: 'tokosaya-ef173',
    storageBucket: 'tokosaya-ef173.appspot.com',
    iosClientId: '958405241222-0976ati127989cdt1ouiga2vnrbsvbs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAkhirToko',
  );
}
